---
-
  hosts: all
  tasks:
    -
      copy:
        dest: /tmp/.
        src: "{{ WORKSPACE }}/target/oms-eureka-service-0.0.1-SNAPSHOT.jar"
      name: "Copy Artifact"
    -
      name: "Run Artifact"
      shell: nohup java -jar /tmp/oms-eureka-service-0.0.1-SNAPSHOT.jar &
